### ISSUE TITLE
How can I add word count?

### ISSUE THREAD

**Issue by simurgh9** [gexplorer/simple-modeline#7]
I love this modeline! I am trying to move from the doom modeline. One feature I can't do without is the word count. In some modes, say LaTeX or Markdown, I like seeing continuous word count. In doom modeline you can set  things like `(setq doom-modeline-continuous-word-count-modes '(markdown-mode latex-mode org-mode))`.

Anyway we could have this here?

**Comment by gexplorer** [comment]
Ok yso you want a word count indicator for certain modes? Let me check doom's implementation

**Comment by simurgh9** [comment]
In doom modeline, we can set this variable `(setq doom-modeline-continuous-word-count-modes '(markdown-mode latex-mode org-mode))` and then when you are in those modes, there is a continuous word count displayed in the modeline. Additionally, if one highlights text then more information about the line, word and characters in the highlighted area are shown.
![demo](https://user-images.githubusercontent.com/43047754/110750626-645b8200-8208-11eb-9b5c-34187adf86c4.png)

**Comment by gexplorer** [comment]
For the word count of the whole buffer I adapted the code from doom:

```lisp
(defvar simple-modeline-word-count-modes nil
  "Major modes with word count activated.")

(defun simple-modeline-segment-word-count ()
  "Display the buffer word count in the mode-line when in a major mode in `simple-modeline-word-count-modes'."
  (if (member major-mode simple-modeline-word-count-modes)
      (format " %dW" (count-words (point-min) (point-max)))))

```

**Comment by simurgh9** [comment]
So is it available from elpa/melpa now?

**Comment by gexplorer** [comment]
I pushed it right now so it should be available from melpa soon.

**Comment by simurgh9** [comment]
I have the following in my configurations,

```lisp
(use-package simple-modeline
  :ensure t
  :custom
    (simple-modeline-word-count-modes '(markdown-mode latex-mode org-mode))
  :hook
    (emacs-startup . simple-modeline-mode))
```

Now when I open a mardown buffer, I don't see the word count on mode-line. Albeit, when I I select text, I see character count like this `+23`. Any help?

**Comment by gexplorer** [comment]
The new segment `simple-modeline-segment-word-count`is not enabled by default. The segments enabled by default are customized by the variable `simple-modeline-segments`and are:

- Left aligned:
  - `simple-modeline-segment-modified`
  - `simple-modeline-segment-buffer-name`
  - `simple-modeline-segment-position`

- Right aligned:
  - `simple-modeline-segment-minor-modes`
  - `simple-modeline-segment-input-method`
  - `simple-modeline-segment-eol`
  - `simple-modeline-segment-encoding`
  - `simple-modeline-segment-vc`
  - `simple-modeline-segment-misc-info`
  - `simple-modeline-segment-process`
  - `simple-modeline-segment-major-mode`

So in order to add the word count left aligned after position:

```elisp
(use-package simple-modeline
  :ensure t
  :custom
  (simple-modeline-word-count-modes '(markdown-mode latex-mode org-mode))
  (simple-modeline-segments
   '((simple-modeline-segment-modified
      simple-modeline-segment-buffer-name
      simple-modeline-segment-position
      simple-modeline-segment-word-count)
     (simple-modeline-segment-minor-modes
      simple-modeline-segment-vc
      simple-modeline-segment-misc-info
      simple-modeline-segment-process
      simple-modeline-segment-major-mode)))
  :hook
  (emacs-startup . simple-modeline-mode))
```

**Comment by simurgh9** [comment]
Here was what I ended up with.

```lisp
(use-package simple-modeline
  :ensure t
  :custom
    (simple-modeline-word-count-modes '(markdown-mode latex-mode org-mode))
  :config
    (push 'simple-modeline-segment-word-count (cdr (last (car simple-modeline-segments))))
  :hook
    (emacs-startup . simple-modeline-mode))
```
